// Dummy data for video analysis
export const videoAnalysisData = [
  {
    id: 1,
    title: 'Dance Tutorial Breakdown',
    status: 'Analyzed',
    statusColor: 'bg-green-500',
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/dc6344f01b-a588851a551c992b0096.png',
    duration: '0:24',
    description: 'Generated 12 hook variations with 94% viral potential',
    scoreLabel: 'Engagement Score',
    scoreValue: '94%',
    scoreColor: 'from-green-500 to-blue-500',
    progress: 94,
    timeAgo: '2 hours ago',
    action: 'View Results',
    viralScore: 94
  },
  {
    id: 2,
    title: 'Recipe Content Analysis',
    status: 'Processing',
    statusColor: 'bg-yellow-500',
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/a1c7a156ea-67da996dee070c9788e1.png',
    duration: '0:31',
    description: 'AI is analyzing structure and engagement patterns...',
    scoreLabel: 'Progress',
    scoreValue: '67%',
    scoreColor: 'from-yellow-500 to-pink-500',
    progress: 67,
    timeAgo: '5 minutes ago',
    action: 'Processing...',
    viralScore: 67
  },
  {
    id: 3,
    title: 'Pasta Recipe Hook Analysis',
    status: 'Analyzed',
    statusColor: 'bg-blue-500',
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/dee9afbfae-6cbfffa306ac73ace59f.png',
    duration: '0:18',
    description: 'Optimized for food niche with trending elements',
    scoreLabel: 'Trend Score',
    scoreValue: '87%',
    scoreColor: 'from-blue-500 to-purple-500',
    progress: 87,
    timeAgo: '1 day ago',
    action: 'View Results',
    viralScore: 87
  },
  {
    id: 4,
    title: 'Fashion Trend Video',
    status: 'Failed',
    statusColor: 'bg-red-300',
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/b41d83299d-0640b815cb9627801370.png',
    duration: '0:29',
    description: 'Analysis failed - unsupported format or corrupted file',
    scoreLabel: 'Error',
    scoreValue: 'Failed',
    scoreColor: 'from-red-300 to-red-500',
    progress: 0,
    timeAgo: '3 hours ago',
    action: 'Retry',
    viralScore: 0
  },
  {
    id: 5,
    title: 'Tech Review Breakdown',
    status: 'Analyzed',
    statusColor: 'bg-purple-500',
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/b41d83299d-0640b815cb9627801370.png',
    duration: '0:45',
    description: 'Educational content with strong retention hooks',
    scoreLabel: 'Education Score',
    scoreValue: '91%',
    scoreColor: 'from-purple-500 to-pink-500',
    progress: 91,
    timeAgo: '6 hours ago',
    action: 'View Results',
    viralScore: 91
  },
  {
    id: 6,
    title: 'Fitness Challenge Video',
    status: 'Analyzed',
    statusColor: 'bg-pink-500',
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/dc6344f01b-a588851a551c992b0096.png',
    duration: '0:29',
    description: 'High-energy content with call-to-action elements',
    scoreLabel: 'Energy Score',
    scoreValue: '96%',
    scoreColor: 'from-pink-500 to-yellow-500',
    progress: 96,
    timeAgo: '1 day ago',
    action: 'View Results',
    viralScore: 96
  }
];